# Generated by Django 3.2.9 on 2021-11-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vegan_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
