# Generated by Django 3.2.9 on 2021-11-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
        migrations.AlterModelTable(
            name='orderstatus',
            table='order_status',
        ),
    ]
