# Generated by Django 3.2.9 on 2021-11-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail_image',
            new_name='thumbnail_image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='sugar_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='vegan_or_not',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
        migrations.AlterModelTable(
            name='reviewcomment',
            table='review_comments',
        ),
    ]
