# Generated by Django 3.2.9 on 2021-12-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211130_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_image_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
